### ISSUE TITLE
storageClass for postgreSQL not adaptable? 

### ISSUE THREAD

**Issue by johanneskastl** [opf/helm-charts#16]
I found no hint on whether or not I can adjust the `storageClass` for the postgreSQL PVC. I found the entry for the openproject PVC:
https://github.com/opf/helm-charts/blob/main/charts/openproject/values.yaml#L263

Is it currently not possible to adjust this?

**Comment by johanneskastl** [comment]
This can be done by setting the following:

```yaml
postgresql:
  global:
    storageClass: my-storage-class-name
```

I'll open up a PR to add a commented example to the `values.yaml`
