### ISSUE TITLE
OpenProject still requires AWS Access/Secret Access Key after using existing secret

### ISSUE THREAD

**Issue by d47zm3** [opf/helm-charts#174]
```
s3:
          enabled: true
          auth:
            existingSecret: "openproject-secrets"
            secretKeys:
              accessKeyId: "aws-access-key"
              secretAccessKey: "aws-secret-access-key"
```
I provided these, secret is there, yet OpenProject screams (openproject-seeder)
```
openproject-seeder-1-w9czq seeder ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key (ArgumentError)
openproject-seeder-1-w9czq seeder
openproject-seeder-1-w9czq seeder           raise ArgumentError, "Missing required arguments: #{missing.join(', ')}"
```
 Also any chance to support IRSA/EKS Pod Identity?
