### ISSUE TITLE
Problems using predefined S3 secret

### ISSUE THREAD

**Issue by famfop** [opf/helm-charts#190]
We are trying to use an S3 object storage for attachments as defined [in the values file](https://github.com/opf/helm-charts/blob/main/charts/openproject/values.yaml#L456). 

For this, we have defined a custom secret with the keys accessKeyId and secretAccessKey (i.e. we did not test setting custom keys). Unfortunately, we are having difficulties getting the values read. As far as we dug, the `secret_s3.yaml` seems to fail to set the values and we wonder if there is a logic error.

We got a bit confused about the template logic [here](https://github.com/opf/helm-charts/blob/main/charts/openproject/templates/secret_s3.yaml#L14) and are wondering if you are able to use a pre-defined secret and we are just doing it wrong or if there is actually a bug?

**Comment by SQLJames** [comment]
Same issue here, Took me a minute to find the issue where those were blank I thought it was a minio issue. I am going to add to this issue with some more information 

I am getting an error in the openproject-seeder-1 job that causes it to fail. 

```
Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden) (Excon::Error::Forbidden)
excon.error.response
  :body              => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The Access Key Id you provided does not exist in our records.</Message><Key>uploads/attachment/file/39/demo_project_teaser.png</Key><BucketName>openproject</BucketName><Resource>/openproject/uploads/attachment/file/39/demo_project_teaser.png</Resource><RequestId>183E05A7BF6AEDA6</RequestId><HostId>0fe7ed0fe73cab1ea494d2869fd1617d06a2ef891e458295ab365b77372162aa</HostId></Error>"
  :cookies           => [
  ]
  :headers           => {
    "accept-ranges"             => "bytes"
    "connection"                => "close"
    "content-length"            => "466"
    "content-type"              => "application/xml"
    "date"                      => "Sat, 10 May 2025 01:18:43 GMT"
    "server"                    => "istio-envoy"
    "strict-transport-security" => "max-age=31536000; includeSubDomains"
    "vary"                      => "Origin,Accept-Encoding"
    "x-amz-id-2"                => "0fe7ed0fe73cab1ea494d2869fd1617d06a2ef891e458295ab365b77372162aa"
    "x-amz-request-id"          => "183E05A7BF6AEDA6"
    "x-content-type-options"    => "nosniff"
    "x-ratelimit-limit"         => "2202"
    "x-ratelimit-remaining"     => "2202"
    "x-xss-protection"          => "1; mode=block"
  }
  :host              => "<correct host>"
  :local_address     => "10.233.111.14"
  :local_port        => 47490
  :method            => "PUT"
  :omit_default_port => true
  :path              => "/openproject/uploads/attachment/file/39/demo_project_teaser.png"
  :port              => 443
  :query             => nil
  :reason_phrase     => "Forbidden"
  :remote_ip         => "172.16.43.127"
  :scheme            => "https"
  :status            => 403
  :status_line       => "HTTP/1.1 403 Forbidden\r\n"
```

using the same access token and secret I have deployed; I am able to put a local file into the openproject bucket I have created. 
```
.\minio.exe alias set openproject <host> <id> <secret>
.\minio.exe ls openproject
[2025-05-09 00:02:18 EDT]     0B openproject/
.\minio.exe put .\test.exe openproject/openproject/uploads/attachment/file/27/test.exe
...wnloads\OperaGXSetup.exe: 4.06 MiB / 4.06 MiB [===========================================================================================] 20.17 MiB/s 0s
```

I am using external secrets to deploy the credentials into my cluster 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openproject-minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: openproject-minio
  data:
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      property: MINIO_ACCESS_KEY
      key: kubernetes/minio/openproject
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      property: MINIO_SECRET_KEY
      key: kubernetes/minio/openproject
```
and I have adjusted the helm chart accordingly 
```
...
  s3:
    enabled: true
    auth:
      existingSecret: openproject-minio
      secretKeys:
        accessKeyId: "MINIO_ACCESS_KEY"
        secretAccessKey: "MINIO_SECRET_KEY"
    bucketName: openproject
    host: host
    port: 443
    pathStyle: true
    signatureVersion: 4
    useIamProfile: false
    directUploads: false
```
